#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Deploy the recipe extractor to Railway"

# ── Stage 1: sign in to Railway ───────────────────────────────────────────
stage "Railway account"
say "We'll deploy from GitHub, so sign in with the GitHub account that owns"
say "vinhbt241/youtube-recipe-extractor."
open_url "https://railway.app"
step "Click 'Log in' and choose 'Continue with GitHub'."
step "Authorize Railway if prompted."
pause "Signed in? Press Enter."

# ── Stage 2: create the project and deploy from GitHub ───────────────────
stage "Create project from GitHub"
say "Railway will read railway.json in the repo (Dockerfile build, start"
say "command, and /up healthcheck are already configured)."
open_url "https://railway.app/dashboard"
step "Click 'New Project', then 'Deploy from GitHub repo'."
step "If asked, install the Railway GitHub app / grant repo access."
step "Select 'vinhbt241/youtube-recipe-extractor' and confirm."
note "Railway builds the image and starts deploying immediately."
note "EXPECTED: the first deploy may crash-loop because PostgreSQL isn't"
note "attached yet (the start command runs db:prepare). That's fine — it"
note "recovers after the next two stages."
pause "Project created and first build started? Press Enter."

# ── Stage 3: attach PostgreSQL ────────────────────────────────────────────
stage "Add PostgreSQL"
say "Railway injects DATABASE_URL automatically when you attach Postgres."
open_url "https://railway.app/dashboard"
step "Open your project's canvas, then click '+ New' (or '+ Create')."
step "Choose 'Database' → 'PostgreSQL'."
step "Wait for the database to show 'Available'."
note "This triggers a redeploy of the web service with DATABASE_URL set."
pause "PostgreSQL attached? Press Enter."

# ── Stage 4: set service variables ────────────────────────────────────────
stage "Set the service variables"
say "Three variables are needed on the web service. We'll collect the two"
say "secrets now, then you paste them into Railway's Variables tab."
say ""
say "Collecting DeepSeek API key:"
open_url "https://platform.deepseek.com/api_keys"
ask_secret DEEPSEEK_API_KEY "Paste your DeepSeek API key (sk-...):"
write_env DEEPSEEK_API_KEY "$DEEPSEEK_API_KEY"

if [[ -f config/master.key ]]; then
  RAILS_MASTER_KEY="$(cat config/master.key)"
  write_env RAILS_MASTER_KEY "$RAILS_MASTER_KEY"
else
  ask_secret RAILS_MASTER_KEY "Paste your RAILS_MASTER_KEY (from config/master.key):"
  write_env RAILS_MASTER_KEY "$RAILS_MASTER_KEY"
fi

open_url "https://railway.app/dashboard"
step "Open your project → the web service → 'Variables' tab."
step "Add each variable below (use the lock icon to mark secrets):"
say ""
say "  RAILS_MASTER_KEY   = $RAILS_MASTER_KEY     (secret)"
say "  DEEPSEEK_API_KEY   = $DEEPSEEK_API_KEY     (secret)"
say "  SOLID_QUEUE_IN_PUMA = true"
say ""
note "DATABASE_URL is already provided by the PostgreSQL service — do not add it."
pause "All three variables added? Press Enter."

# ── Stage 5: generate a domain and verify ─────────────────────────────────
stage "Generate a domain and verify"
say "Give the service a public URL and test it end to end."
open_url "https://railway.app/dashboard"
step "Open the web service → Settings → Networking → 'Generate Domain'."
step "Copy the https://...up.railway.app URL."
step "If the service is stopped (after the early crash-loop), click 'Deploy'."
say ""
say "Open the URL in your browser, paste a cooking-video YouTube link, and"
say "submit. Extraction takes ~30–60s (yt-dlp + DeepSeek), then the page"
say "shows ingredients and steps."
pause "Recipe page renders? Press Enter."

confirm "Everything working? Commit the wizard for re-use" \
  && note "run: git add scripts/deploy-railway.sh && git commit" \
  || note "leave it uncommitted; delete later with: rm scripts/deploy-railway.sh"

finish
